import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/global/ThemeProvider";
import { getUserData } from "@/actions/set-user-data";
import SetUserData from "@/components/main/SetUserData";
import { TanstackQueryProvider } from "@/components/global/TanstackQueryProvider";
import "./globals.css";
const poppins = Poppins({ weight: ["500", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getUserData();
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${poppins.className} h-full flex flex-col min-h-screen`}
      >
        <TanstackQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SetUserData data={data} />
            {children}
            <Toaster richColors position="top-right" />
          </ThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
