import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/global/ThemeProvider";
import { getUserData } from "@/actions/set-user-data";
import SetUserData from "@/components/main/SetUserData";
import { TanstackQueryProvider } from "@/components/global/TanstackQueryProvider";
import "./globals.css";
import { getMembers } from "@/actions/member";
const poppins = Poppins({ weight: ["500", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getDoctors = async () => {
  const data = await getMembers("DOCTOR");
  const filtered = data.data?.map((doctor) => {
    return {
      id: doctor.id,
      name: doctor.name,
      gender: doctor.gender,
      image: doctor.image,
      masterId: doctor.masterId,
    };
  });
  return filtered;
};

export type FilteredDoctors =
  | {
      id: string;
      name: string | null;
      gender: string | null;
      image: string | null;
      masterId: string | null;
    }[]
  | undefined;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getUserData();
  const doctors = await getDoctors();

  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${poppins.className} h-full flex flex-col min-h-screen`}
      >
        <TanstackQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SetUserData data={data} doctors={doctors} />
            {children}
            <Toaster richColors position="top-right" />
          </ThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
